### ISSUE TITLE
About TEdBench 

### ISSUE THREAD

**Issue by gebaltso** [witcherofresearch/Forgedit#2]
Could you please provide the way we can download the TEdBench text guided image editing benchmark?

Also is it possible to use your implementation with stable diffusion 2.1? 

Thanks in advance.

**Comment by witcherofresearch** [comment]
Hi, gebaltso, you could download TEdBench from Imagic's official repo https://github.com/imagic-editing/imagic-editing.github.io/tree/main/tedbench
And Forgedit works with Stable Diffusion 2.1
