### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by xu-pping** [witcherofresearch/Forgedit#3]
Hello, can this project run on GPUs of V100,16G

**Comment by witcherofresearch** [comment]
Hi, I never ran this project on V100. However, I think there should be no problems to run this project on V100 if you adjust the batch size in the finetuning stage in order to fit in the 16GB GPU memory.

**Comment by witcherofresearch** [comment]
Hi, I never ran this project on V100. However, I think there should be no promblems if you adjust the batch size to fit in the GPU memory.
