### ISSUE TITLE
The edited image is blurry.

### ISSUE THREAD

**Issue by xiaohetongxue** [witcherofresearch/Forgedit#6]
After reproducing the code, the resulting image is very blurry. Have you encountered this issue?
![捕获](https://github.com/witcherofresearch/Forgedit/assets/63027251/00985be4-6743-4e2c-b30a-3d9ed2de27d4)

**Comment by witcherofresearch** [comment]
hi, never encounter such a phenomenon. Would you provide some information, for example, input image, target prompt, and hyperparameters you are using, so that I could help locate the problem?
